---
title: "LaLiga123_17-18_stats"
author: "Luis Alberto Bayo y Miguel Ángel Bermejo Águeda"
date: "15 de abril de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r webscraping code, include=FALSE, warning=FALSE}

# Se incluye la librería 'rvest' para poder hacer uso de las funciones que incorpora para las tareas de scraping. Esta librería ayuda además a responder a páginas web que declaran codificaciones incorrectas.
#install.packages('rvest')
library(rvest)

# Se almacena en la variable 'teams' el nombre de los 22 equipos que componen la segunda división de fútbol, de los se pretende obtener los datos. Estos atributos se hacen coincidir con el nombre que tiene cada uno de los equipos en el path de la url que muestra sus respectivos datos.
teams <- c("alcorcon", "albacete", "osasuna", "lugo", "numancia", "tenerife", "reus-deportiu","gimnastic", "cultural-leonesa", "cadiz", "cordoba", "barcelona-b", "granada", "lorca", "rayo", "oviedo", "sporting", "valladolid", "zaragoza", "huesca", "sevilla-atletico", "almeria")

# Inicialización  del dataframe con el que se va a trabajar.
finaldata <- data.frame()

# Se almacena en 'urlcabecera' la ruta común dónde se realiza el proceso de web scraping.
urlcabecera <- read_html("https://www.laliga.es/estadisticas-historicas/plantillas/segunda/2017-18/")

# Instrucción que recoge en un array el nombre de los atributos de la tabla que da forma al dataset que se quiere generar. Estos atributos se ubican con elementos "th" dentro del código HTML. Se almacena por tanto, las cadenas de texto de esos elementos en 'col_name'.  
col_name <- urlcabecera %>% html_nodes("th") %>% html_text()

# Generación de una iteración para recorrer todos los valores de 'teams', es decir,  para poder obtener los datos de cada uno de los equipos a estudio.
for (i in 1:length(teams)) {
  # url toma la ruta de la web propia de cada equipo.
  url <- read_html(paste("https://www.laliga.es/estadisticas-historicas/plantillas/segunda/2017-18/", teams[i], sep=""))
  
  # Los datos deseados de cada jugador están etiquetdos como elementos "td" en el código HTML de la web.
  mydata <- url %>% html_nodes("td") %>% html_text()
  
  # Condición para la primera vez que se recorra el bucle FOR
  if (i == 1)  {
   
    # 'finaldata' almacena en un dataframe de 10 columnas los valores obtenidos de los jugadores de un equipo almacenados en el array 'mydata'.
    finaldata <- data.frame(matrix(mydata, ncol=10, byrow=TRUE))
    
    # Se contruye la cabecera para el dataframe 'finaldata' con los valores anteriormente obtenidos y almacenados en 'col_name'.
    names(finaldata) <- col_name
    
    # Se añade una nueva columna 'Equipo' que distinga el equipo al que pertenece cada jugador encontrado.
    finaldata ["Equipo"] <- teams[i]
    
  }
  
  else {
    
    # Se crea un nuevo dataframe temporal 'finaldatatemporal' que almacena los datos de los equipos recorridos según se accede a la iteracción
    finaldatatemporal <- data.frame(matrix(mydata, ncol=10, byrow=TRUE))
  
    # Al igual que para 'finaldata', se contruye la cabecera para el dataframe 'finaldatatemporal' con los valores anteriormente obtenidos y almacenados en 'col_name'.
    names(finaldatatemporal) <- col_name
    
    # Al igual que para 'finaldata', se añade una nueva columna 'Equipo' que distinga el equipo al que pertenece cada jugador encontrado.
    finaldatatemporal$Equipo <- teams[i]
    
    # Por último se unen sucesivamente todos los datasets para conformar el dataframe final.
    finaldata <- rbind(finaldata, finaldatatemporal)
    
  }
  
  
}

# Se realizada el borrad de las comas (",") que aparecen en algunos nombres de jugadores para que el fichero .CSV generado no se vea afectado por ello.
finaldata$Jugador <- gsub(",",".",finaldata$Jugador)
    
# Finalmente se genera el fichero .CSV 'LaLiga123_17-18_stats' con los datos obtenidos.
write.csv(finaldata, file = "LaLiga123_17-18_stats.csv", row.names=FALSE)


```
