---
title: "LaLiga2"
author: "Luis Alberto Bayo & Miguel Ángel Bermejo Águeda"
date: "9 de abril de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)

teams <- c("alcorcon", "albacete", "osasuna", "lugo", "numancia", "tenerife", "reus-deportiu","gimnastic", "cultural-leonesa", "cadiz", "cordoba", "barcelona-b", "granada", "lorca", "rayo", "oviedo", "sporting", "valladolid", "zaragoza", "huesca", "sevilla-atletico", "almeria")

# inicializamos el dataframe con el que vamos a trabajar
finaldata <- data.frame()
urlcabecera <- read_html("https://www.laliga.es/estadisticas-historicas/plantillas/segunda/2017-18/")
col_name <- urlcabecera %>% html_nodes("th") %>% html_text()

for (i in 1:length(teams)) {
  url <- read_html(paste("https://www.laliga.es/estadisticas-historicas/plantillas/segunda/2017-18/", teams[i], sep=""))
  mydata <- url %>% html_nodes("td") %>% html_text()
  
  if (i == 1)  {
   
    finaldata <- data.frame(matrix(mydata, ncol=10, byrow=TRUE))
    names(finaldata) <- col_name
    
    #Incluimos la columna equipo poniendole el nombre del equipo que estamos recorriendo teams[i]
    finaldata ["Equipo"] <- teams[i]
    
  }
  
  else {
    finaldatatemporal <- data.frame(matrix(mydata, ncol=10, byrow=TRUE))
    names(finaldatatemporal) <- col_name
    finaldatatemporal$Equipo <- teams[i]
    
    finaldata <- rbind(finaldata, finaldatatemporal)
    
  }
  
  
}

# Eliminamos las comas de los nombres de los jugadores, para que el fichero CSV no se vea afectado por ello.
finaldata$Jugador <- gsub(",",".",finaldata$Jugador)
    
write.csv(finaldata, file = "liga123_17-18.csv", row.names=FALSE)


```

